# Broadcasting en NumPy
El broadcasting es la capacidad de NumPy para realizar operaciones entre arrays de diferentes tamaños, expandiendo uno de ellos automáticamente sin necesidad de copiar datos, siempre que cumplan ciertas reglas.

Reglas básicas del broadcasting:

1. Si las dimensiones no son iguales, NumPy “completa” las más cortas con 1s a la izquierda.
2. En cada dimensión:
    - Si los tamaños son iguales → se pueden combinar.
    - Si uno de los tamaños es 1 → se repite ese valor.
    - Si son distintos y ninguno es 1 → error.

In [2]:
import numpy as np

a = np.array([1, 2, 3])       # shape: (3,)
b = np.array([[10], [20], [30]])  # shape: (3, 1)
print(a)
print(b)
# Broadcasting: b se expande en columnas, a se expande en filas
print(a + b)

[1 2 3]
[[10]
 [20]
 [30]]
[[11 12 13]
 [21 22 23]
 [31 32 33]]


## Tipos de multiplicación de matrices en NumPy
NumPy tiene tres formas principales de multiplicar:

- Multiplicación elemento a elemento (*)
Multiplica elemento con elemento en la misma posición.

In [7]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A * B)

[[ 5 12]
 [21 32]]


- Producto matricial (@ o np.matmul)  
Hace la multiplicación de matrices como en álgebra lineal.

In [8]:
print(A @ B)

[[19 22]
 [43 50]]


- Producto escalar (np.dot)  
En 2D es igual que @, pero para vectores 1D calcula el producto punto.

In [3]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(np.dot(v1, v2))  # 1*4 + 2*5 + 3*6 = 32

32


| Operación           | Símbolo        | Dimensiones compatibles    | Uso típico            |
| ------------------- | -------------- | -------------------------- | --------------------- |
| Elemento a elemento | `*`            | Igual forma o broadcasting | Escalar cada elemento |
| Producto matricial  | `@` / `matmul` | `(m, n) @ (n, p)`          | Álgebra lineal        |
| Producto punto      | `np.dot`       | `(n,) · (n,)` o matrices   | Producto escalar      |